name: 逐文件并行下载并上传至Alist
on:
  workflow_dispatch:
    inputs:
      folder_path:
        description: '需要下载的文件夹路径'
        required: true
        default: '/dav/迅雷x/我的云盘/2024年10月合集'
      upload_path:
        description: '上传到的目标路径'
        required: true
        default: '/dav/里番'

jobs:
  AlistJob:
    runs-on: ubuntu-latest
    steps:
      - name: 安装所需工具
        run: |
          sudo apt update
          sudo apt install -y curl jq parallel

      - name: 下载并解压 Alist
        run: |
          curl -L -o alist.tar.gz https://github.com/alist-org/alist/releases/download/v3.30.0/alist-linux-amd64.tar.gz
          tar -xzf alist.tar.gz
          mkdir data
          mv config.json data/config.json
          nohup ./alist server > nohupcmd.out 2>&1 &
        env:
          ALIST_ADMIN_PASSWORD: admin

      - name: 等待 Alist 启动
        run: sleep 60s

      - name: 获取文件夹中的文件列表
        id: list-files
        run: |
          API_URL="http://localhost:5244/api/public/path"
          FOLDER_PATH="${{ inputs.folder_path }}"
          FILE_LIST=$(curl -s -X POST "$API_URL" -H "Content-Type: application/json" \
            -d "{\"path\":\"$FOLDER_PATH\"}" | jq -r '.data.content[] | select(.type=="file") | .name')

          if [ -z "$FILE_LIST" ]; then
            echo "未发现任何文件。"
            exit 1
          fi

          echo "$FILE_LIST" > files_to_process.txt
        env:
          ALIST_ADMIN_PASSWORD: admin

      - name: 并行下载并上传文件
        run: |
          DOWNLOAD_BASE="http://localhost:5244${{ inputs.folder_path }}"
          UPLOAD_BASE="http://localhost:5244${{ inputs.upload_path }}"

          cat files_to_process.txt | parallel -j 10 "
            # 下载文件
            curl -o {1} $DOWNLOAD_BASE/{1} --user admin:admin && 
            # 上传文件
            curl -T {1} $UPLOAD_BASE/{1} --user admin:admin && 
            # 删除本地文件
            rm -f {1}
          "
