name: 0上传至Alist
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      path:
        description: '下载路径'
        required: true
        default: 'Onedriver'

jobs:
  Onedriver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 增加可用空间 (删除dotnet, android、haskell、CodeQL)
        shell: bash
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y nodejs curl fuse

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: 生成Alist的配置文件
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "config.json"
          json: ${{ secrets.ALIST_CONFIG }}
          
      - name: 运行Alist
        run: |
          curl -L -o alist.tar.gz https://github.com/alist-org/alist/releases/download/v3.30.0/alist-linux-amd64.tar.gz
          tar -xzf alist.tar.gz
          mkdir data
          mv config.json data/config.json
          nohup ./alist server > nohupcmd.out 2>&1 &
          ls ${{github.workspace}}/data
        env:
          ALIST_ADMIN_PASSWORD: admin

      - name: 等Alist运行起来(大概2分钟)
        run: sleep 120s
        shell: bash

      - name: 生成rclone配置文件
        run: |
          cat << EOF > rclone.conf
          [alist]
          type = webdav
          url = http://localhost:5244/dav/
          vendor = other
          user = admin
          pass = admin
          EOF

      - name: 复制文件到另一个Alist文件夹
        run: |
          # 复制Alist的source文件夹到destination文件夹
          rclone copy alist:/迅雷x/我的云盘/转移 alist:/里番 --config=rclone.conf

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v1.2.3
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
