name: 0上传至Alist
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      path:
        description: '下载路径'
        required: true
        default: 'Onedriver'

jobs:
  Onedriver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 增加可用空间 (删除dotnet, android、haskell、CodeQL)
        shell: bash
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL

      - name: Aria2 Install
        run: |
            sudo apt update
            sudo apt install -y aria2 nodejs curl

      - name: 生成Alist的配置文件
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "config.json"
          json: ${{ secrets.ALIST_CONFIG }}
          
      - name: 运行Alist
        run: |
          curl -L -o alist.tar.gz https://github.com/alist-org/alist/releases/download/v3.30.0/alist-linux-amd64.tar.gz
          tar -xzf alist.tar.gz
          mkdir data
          mv config.json data/config.json
          nohup ./alist server > nohupcmd.out 2>&1 &
          ls ${{github.workspace}}/data
        env:
          ALIST_ADMIN_PASSWORD: admin

      - name: 等Alist运行起来(大概2分钟)
        run: sleep 120s
        shell: bash
          
      - name: 'Download file'
        run: |
          aria2c --conf $GITHUB_WORKSPACE/aria2.conf --seed-time=0 -d downloads -c 'http://localhost:5244/dav/%E8%BF%85%E9%9B%B7x/%E6%88%91%E7%9A%84%E4%BA%91%E7%9B%98/%E8%BD%AC%E7%A7%BB/2024%E5%B9%B410%E6%9C%88%E5%90%88%E9%9B%86/CHS/[241025][%E9%AD%94%E4%BA%BA]%E3%83%A1%E3%82%AB%E6%8A%80%E5%B8%AB%E3%83%AA%E3%82%B9%E3%82%BF%E3%81%AE%E5%A4%A7%E5%86%92%E9%99%BA%20%E7%AC%AC%E4%B8%80%E8%A9%B1%20%E9%9B%BB%E6%B3%A2%E3%82%B8%E3%83%A3%E3%83%83%E3%82%AF%E3%81%A7%E5%A4%A7%E6%B7%B7%E4%B9%B1!%20%E3%83%8C%E3%83%AB%E3%83%8C%E3%83%AB%E8%A7%A6%E6%89%8B%E3%82%92%E6%89%93%E3%81%A1%E5%80%92%E3%81%9B%EF%BC%81.chs.mp4' -o '[241025][魔人]メカ技師リスタの大冒険 第一話 電波ジャックで大混乱! ヌルヌル触手を打ち倒せ！.chs.mp4' 

      - name: 上传到Alist
        run: |
          curl -v -u 'admin:admin' -T 'downloads/[241025][魔人]メカ技師リスタの大冒険 第一話 電波ジャックで大混乱! ヌルヌル触手を打ち倒せ！.chs.mp4' http://localhost:5244/dav/里番/[241025][魔人]メカ技師リスタの大冒険 第一話 電波ジャックで大混乱! ヌルヌル触手を打ち倒せ！.chs.mp4
          
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v1.2.3
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
